#!/bin/bash
# Setup script to fetch agent ARN and Cognito config from AWS
# Mimics the behavior of test/connect_agent.py and test/utils.py

set -e

echo "🔧 Setting up frontend environment..."

# Check for required parameter
COGNITO_STACK_NAME=${1:-"cognito-stack-a2a"}
echo "📋 Using Cognito stack name: $COGNITO_STACK_NAME"

# Get AWS region and account ID
echo "📍 Detecting AWS region and account..."
REGION=$(aws configure get region)
if [ -z "$REGION" ]; then
    REGION="us-west-2"
    echo "⚠️  No region configured, using default: $REGION"
else
    echo "✅ Region: $REGION"
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "✅ Account ID: $ACCOUNT_ID"

# Fetch host agent runtime ID from SSM
echo "📦 Fetching host agent runtime ID from SSM..."
RUNTIME_ID=$(aws ssm get-parameter --name "/hostagent/agentcore/runtime-id" --query "Parameter.Value" --output text)

if [ -z "$RUNTIME_ID" ]; then
    echo "❌ Failed to fetch runtime ID from SSM parameter: /hostagent/agentcore/runtime-id"
    echo "   Make sure the host agent is deployed and SSM parameter exists."
    exit 1
fi

echo "✅ Runtime ID: $RUNTIME_ID"

# Construct agent ARN
AGENT_ARN="arn:aws:bedrock-agentcore:${REGION}:${ACCOUNT_ID}:runtime/${RUNTIME_ID}"
echo "✅ Constructed Agent ARN: $AGENT_ARN"

# Fetch Cognito configuration from CloudFormation stack outputs
echo "🔐 Fetching Cognito configuration from CloudFormation..."
STACK_OUTPUTS=$(aws cloudformation describe-stacks --stack-name "$COGNITO_STACK_NAME" --query "Stacks[0].Outputs" --output json)

if [ -z "$STACK_OUTPUTS" ] || [ "$STACK_OUTPUTS" == "null" ]; then
    echo "❌ Failed to fetch CloudFormation stack outputs for: $COGNITO_STACK_NAME"
    echo "   Make sure the Cognito stack is deployed."
    exit 1
fi

# Extract values from stack outputs
CLIENT_ID=$(echo "$STACK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="WebUserPoolClientId") | .OutputValue')
DISCOVERY_URL=$(echo "$STACK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="DiscoveryUrl") | .OutputValue')
COGNITO_DOMAIN=$(echo "$STACK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="CognitoDomain") | .OutputValue')
USER_POOL_ID=$(echo "$DISCOVERY_URL" | cut -d'/' -f4)

# Construct token endpoint from discovery URL
# Discovery URL format: https://cognito-idp.{region}.amazonaws.com/{user_pool_id}/.well-known/openid-configuration
TOKEN_ENDPOINT="https://cognito-idp.${REGION}.amazonaws.com/${USER_POOL_ID}/oauth2/token"

echo "✅ Cognito Client ID: $CLIENT_ID"
echo "✅ User Pool ID: $USER_POOL_ID"
echo "✅ Cognito Domain: $COGNITO_DOMAIN"
echo "✅ Token Endpoint: $TOKEN_ENDPOINT"

# Create .env file
echo "📝 Creating .env file..."
cat > .env << EOF
# Auto-generated by setup-env.sh
# Generated on: $(date)

# AWS Configuration
VITE_AWS_REGION=${REGION}

# Host Agent Configuration
VITE_AGENT_ARN=${AGENT_ARN}

# Cognito Configuration (for Amplify Auth)
VITE_COGNITO_USER_POOL_ID=${USER_POOL_ID}
VITE_COGNITO_USER_POOL_CLIENT_ID=${CLIENT_ID}
VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}
VITE_COGNITO_TOKEN_ENDPOINT=${TOKEN_ENDPOINT}
EOF

echo "✅ .env file created successfully!"
echo ""
echo "🚀 You can now run the frontend:"
echo "   npm run dev"
